services:
  identitymanagement:
    image: identitymanagement
    build:
      context: .
      dockerfile: IdentityManagement/Dockerfile

  identityservice:
    image: identityservice
    build:
      context: .
      dockerfile: IdentityService/Dockerfile

  shipmentservice:
    image: shipmentservice
    build:
      context: .
      dockerfile: ShipmentService/Dockerfile

  shared.contracts:
    image: shared.contracts
    build:
      context: .
      dockerfile: Shared.Contracts/Dockerfile

